export const SEOUL_CENTER_LONGITUDE = 126.9743513;
export const SEOUL_CENTER_LATITUDE = 37.57297651;

export const INITIAL_MAP_CENTER = {
  lat: SEOUL_CENTER_LATITUDE,
  lng: SEOUL_CENTER_LONGITUDE,
};

export const INITIAL_ZOOM_LEVEL = 8;
