name: CI/CD to EC2

on:
    push:
        branches: ['dev']
    pull_request:
        branches: ['dev']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. 리포지토리 체크아웃
            - name: Checkout repository
              uses: actions/checkout@v4

            # 2. pnpm 설치
            - name: Set up pnpm
              run: npm install -g pnpm

            # 3. Node.js 환경 설정
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'

            # 4. 의존성 설치 & 빌드
            - name: Install dependencies & Build
              run: |
                  pnpm install
                  pnpm build

            # 5. SSH로 EC2 접속 후 배포
            - name: Deploy to EC2
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
                    cd ~/eye-on-frontend
                    pnpm install
                    pnpm run build
                    pm2 restart "eye on frontend" || pm2 start pnpm --name "eye on frontend" -- run start
                  EOF
