name: Node.js CI/CD to EC2

on:
    push:
        branches: ['dev']
    pull_request:
        branches: ['dev']

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]
        steps:
            # 1. 리포지토리 코드 체크아웃
            - name: Checkout repository
              uses: actions/checkout@v4

            # 2. pnpm 설치 (버전 9.15.4)
            - name: Set up pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9.15.4

            # 3. Node.js 환경 설정 (노드 버전 '22.x', pnpm 캐싱 사용)
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'pnpm'
                  cache-dependency-path: ./eye-on-frontend/pnpm-lock.yml

            - name: Install pnpm
              run: npm install -g pnpm

            # 4. 프론트엔드 폴더에서 의존성 설치
            - name: Install dependencies in frontend
              run: pnpm install

            # 5. 프론트엔드 폴더에서 빌드 실행
            - name: Build frontend
              run: pnpm build

            - name: Setup SSH and Deploy
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
                    cd ~/eye-on-frontend
                    pnpm install
                    pnpm run build
                    pm2 restart "eye on frontend" || pm2 start pnpm --name "eye on frontend" -- run start
                  EOF
